global-settings:
  despawn-interval: 10
  inactive-around-spawn-radius: 10
  version: 5
worlds:
  world:
    height: 24
    health: 1
    ratio: 0.8
    mobs:
    - zombie
    - creeper
    - skeleton
    - spider
    - cave spider
    - enderman
    - endermite
    - silverfish
    - slime
    - witch
    custom:
      zombie:
        health: 1.5
        ratio: 1
