global-settings:
  async-despawn: true
  despawn-interval: 10
  ignore-named-mobs: true
  version: 2
worlds:
  world:
    height: 24
    health: 1
    ratio: 0.8
    mobs:
    - zombie
    - creeper
    - skeleton
    - spider
    - cave spider
    - enderman
    - endermite
    - silverfish
    - slime
    - witch
    custom:
      zombie:
       health: 1.5
       ratio: 1
